<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.6.2 setup script
 * Date: Wed, 01 Jun 2016 06:12:08 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: dbtestitoc01 [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'rds01.prod';
$cfg['Servers'][$i]['host'] = 'robol.clisvqsrzqhf.ap-southeast-2.rds.amazonaws.com';
$cfg['Servers'][$i]['port'] = 3306;
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
/* End of servers configuration */

$cfg['blowfish_secret'] = '574e75d4f3dee5.86019297';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
